endpoint: wss://altair.api.onfinality.io/public-ws
mock-signature-host: true
block: ${env.ALTAIR_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5

import-storage:
  # Sudo:
  #   Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        - providers: 1
          data:
            free: "100000000000000000000000000000000"
  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  Elections:
    Members:
      - who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        stake: "1000000000000000000000000"
        deposit: "1000000000000000000000000"
  TechnicalCommittee:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  TechnicalCommitteeMembership:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
