endpoint: wss://fullnode.centrifuge.io
mock-signature-host: true
block: ${env.CENTRIFUGE_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5

import-storage:

  System:
    # Fund addresses with native currency
    Account:
      -
        -
          - "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" # Alice
        - providers: 1
          data:
            free: "1000000000000000000000000"
      -
        -
          - "4eZq6YogeXHKvjLhHjNKoTzv6MLESn7MkBEQSvctxAnAT82t" # Bob
        - providers: 1
          data:
            free: "1000000000000000000000000"
      -
        -
          - "4eZq6YogeXHKvjLhHjNKoTzv6MLESn7MkBEQSvctxAnAT82t" # Charlie
        - providers: 1
          data:
            free: "1000000000000000000000000"
      -
        -
          - 14W74iMbQoRceoyogC9rjxTrig7raDKNevjot2UnZTqs5vZa # Ledger
        - providers: 1
          data:
            free: '10000000000000000000'
  Council:
    # Set Alice as single council member
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
  Elections:
    Members:
      - who: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        stake: "10000000000000000000000"
        deposit: "10000000000000000000000"
  OrmlTokens:
    # Fund addresses with foreign currencies
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 1 # Tether USDT
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 2 # Axelar USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 3 # Acala dollar (AUSD)
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 4 # GLMR
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 5 # DOT
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 6 # USD Coin USDC
        - free: 1000000000000
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100001 # LP Ethereum Wrapped USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100002 # LP Base Wrapped USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100003 # LP Arbitrum Wrapped USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100004 # LP Celo Wrapped Wormhole USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100005 # LP Wrapped FRAX
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - ForeignAsset: 100006 # LP Celo Wrapped USDC
        - free: "1000000000000000000000"
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - LocalAsset: 1 # Local USDC
        - free: "10000000000000"
  Proxy:
    # Example to set proxy
    Proxies:
      -
        -
          - 4gJcbk2V9JLmYkMPDeeYZ2Kmtf6J6GqYfdNw4qdzzSzBppDW # The address which sets a proxy
        -
          -
            - delegate: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" # The proxy account address
            - proxyType: "Any"
            - delay: 0
          - "350000000000000000"
  Permissions:
    # Example to set permissions
    Permission:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - Pool: 4139607887
        -
          poolAdmin:
            bits: 59
          currencyAdmin:
            bits: 0
          permissionedAssetHolder:
            info: null
          trancheInvestor:
            info: []
  OraclePriceCollection:
    # Example to set oracle feeder
    CollectionInfo:
      -
        -
          - 4139607887
        - feeders:
          - system:
              signed: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY


